"""
FOMO Detector - Phát hiện hành vi FOMO (Fear of Missing Out)
"""

from dataclasses import dataclass, field
from typing import Optional, List
from datetime import datetime


@dataclass
class MarketContext:
    """Market context at time of trade"""
    price_change_pct_1h: float = 0.0
    price_change_pct_24h: float = 0.0
    is_near_local_high: bool = False
    volume_ratio: float = 1.0  # current volume / avg volume


@dataclass
class Alert:
    """Alert generated by detector"""
    alert_type: str
    severity: str  # 'INFO', 'MEDIUM', 'HIGH', 'CRITICAL'
    score: int  # 0-100
    reasons: List[str] = field(default_factory=list)
    recommendation: str = ""
    
    def to_dict(self) -> dict:
        return {
            "alert_type": self.alert_type,
            "severity": self.severity,
            "score": self.score,
            "reasons": self.reasons,
            "recommendation": self.recommendation
        }


class FOMODetector:
    """
    Phát hiện FOMO dựa trên:
    1. Price đã pump >X% trong Y phút trước entry
    2. Keywords khẩn cấp trong note
    3. Entry ngay sau breakout/pump
    """
    
    FOMO_KEYWORDS = [
        # Vietnamese
        "phải vào ngay", "mua gấp", "sợ lỡ", "không kịp",
        "đang bay", "pump rồi", "fomo", "all in", "chốt liền",
        "bắt đáy", "đuổi giá", "lỡ tàu", "sợ miss",
        # English
        "must buy now", "hurry", "missing out", "can't miss",
        "pump", "going up fast", "get in now", "before too late"
    ]
    
    def detect(
        self, 
        notes: Optional[str], 
        market_context: Optional[MarketContext] = None,
        entry_price: Optional[float] = None
    ) -> Optional[Alert]:
        """
        Detect FOMO behavior.
        
        Args:
            notes: Trade notes from user
            market_context: Market conditions at entry
            entry_price: Entry price of the trade
            
        Returns:
            Alert if FOMO detected, None otherwise
        """
        score = 0
        reasons = []
        
        # Check 1: Price pump before entry (if market context available)
        if market_context:
            price_change_1h = market_context.price_change_pct_1h
            
            if price_change_1h > 8:
                score += 45
                reasons.append(f"🚀 Price đã tăng {price_change_1h:.1f}% trong 1h qua - FOMO RISK CAO!")
            elif price_change_1h > 5:
                score += 35
                reasons.append(f"📈 Price đã tăng {price_change_1h:.1f}% trong 1h qua")
            elif price_change_1h > 3:
                score += 20
                reasons.append(f"📊 Price đã tăng {price_change_1h:.1f}% trong 1h qua")
            
            # Check if entry is near local high
            if market_context.is_near_local_high:
                score += 25
                reasons.append("⚠️ Entry gần đỉnh local (top 2%)")
            
            # High volume can indicate FOMO buying
            if market_context.volume_ratio > 3:
                score += 15
                reasons.append(f"📊 Volume cao bất thường ({market_context.volume_ratio:.1f}x trung bình)")
        
        # Check 2: Keywords in notes
        if notes:
            note_lower = notes.lower()
            matched_keywords = [k for k in self.FOMO_KEYWORDS if k in note_lower]
            
            if matched_keywords:
                keyword_score = min(len(matched_keywords) * 15, 40)
                score += keyword_score
                reasons.append(f"🔍 Phát hiện keywords FOMO: {', '.join(matched_keywords[:3])}")
        
        # Generate alert if score is high enough
        if score >= 40:
            severity = self._get_severity(score)
            
            if score >= 70:
                recommendation = "🛑 DỪNG LẠI! Chờ pullback hoặc skip trade này. FOMO thường dẫn đến entry xấu."
            elif score >= 50:
                recommendation = "⚠️ Cân nhắc: Giảm size 50%, đặt SL chặt, hoặc chờ pullback."
            else:
                recommendation = "💡 Lưu ý: Kiểm tra lại lý do vào lệnh. Có phải FOMO không?"
            
            return Alert(
                alert_type="FOMO",
                severity=severity,
                score=score,
                reasons=reasons,
                recommendation=recommendation
            )
        
        return None
    
    def _get_severity(self, score: int) -> str:
        """Get severity level based on score"""
        if score >= 80:
            return "CRITICAL"
        elif score >= 60:
            return "HIGH"
        elif score >= 40:
            return "MEDIUM"
        else:
            return "INFO"
