"""
Revenge Trading Detector - Phát hiện hành vi giao dịch trả thù
"""

from dataclasses import dataclass, field
from typing import Optional, List
from datetime import datetime, timedelta


@dataclass
class TradeInfo:
    """Trade information for analysis"""
    pnl: float = 0.0
    pnl_pct: float = 0.0
    quantity: float = 0.0
    exit_time: Optional[datetime] = None


@dataclass
class SessionStats:
    """User session statistics"""
    last_trades: List[TradeInfo] = field(default_factory=list)
    avg_position_size: float = 0.0
    session_pnl: float = 0.0
    current_drawdown_pct: float = 0.0


@dataclass
class Alert:
    """Alert generated by detector"""
    alert_type: str
    severity: str
    score: int
    reasons: List[str] = field(default_factory=list)
    recommendation: str = ""
    
    def to_dict(self) -> dict:
        return {
            "alert_type": self.alert_type,
            "severity": self.severity,
            "score": self.score,
            "reasons": self.reasons,
            "recommendation": self.recommendation
        }


class RevengeTradingDetector:
    """
    Phát hiện Revenge Trading dựa trên:
    1. Có loss đáng kể trong session gần đây
    2. Entry nhanh sau loss (<10 phút)
    3. Position size tăng so với trước
    4. Keywords thể hiện tâm lý trả thù
    """
    
    REVENGE_KEYWORDS = [
        # Vietnamese
        "gỡ gạc", "gỡ lại", "trả thù", "thua đủ rồi",
        "phải thắng", "không thể thua nữa", "lấy lại",
        "đòi lại", "bù lỗ", "phục hận", "quyết gỡ",
        "tăng size", "đánh lớn hơn", "all in gỡ",
        # English
        "revenge trade", "get it back", "must win",
        "can't lose again", "recover losses", "double down",
        "averaging down", "bigger position", "make it back"
    ]
    
    def detect(
        self,
        notes: Optional[str],
        current_quantity: float,
        entry_time: datetime,
        session_stats: Optional[SessionStats] = None
    ) -> Optional[Alert]:
        """
        Detect revenge trading behavior.
        
        Args:
            notes: Trade notes from user
            current_quantity: Position size of current trade
            entry_time: Entry time of current trade
            session_stats: Statistics from current trading session
            
        Returns:
            Alert if revenge trading detected, None otherwise
        """
        score = 0
        reasons = []
        
        if session_stats and session_stats.last_trades:
            last_trade = session_stats.last_trades[-1]
            
            # Check 1: Recent significant loss
            if last_trade.pnl < 0:
                loss_pct = abs(last_trade.pnl_pct)
                
                if loss_pct > 5:
                    score += 40
                    reasons.append(f"💸 Vừa thua lỗ LỚN: {loss_pct:.1f}%")
                elif loss_pct > 2:
                    score += 30
                    reasons.append(f"💸 Vừa thua: {loss_pct:.1f}%")
                elif loss_pct > 0.5:
                    score += 15
                    reasons.append(f"📉 Vừa thua: {loss_pct:.1f}%")
            
            # Check 2: Quick entry after loss
            if last_trade.exit_time:
                time_since_last = (entry_time - last_trade.exit_time).total_seconds() / 60
                
                if last_trade.pnl < 0:
                    if time_since_last < 5:
                        score += 40
                        reasons.append(f"⚡ Vào lệnh quá nhanh: chỉ {time_since_last:.0f} phút sau khi thua!")
                    elif time_since_last < 10:
                        score += 30
                        reasons.append(f"⚡ Vào lệnh nhanh: {time_since_last:.0f} phút sau khi thua")
                    elif time_since_last < 20:
                        score += 15
                        reasons.append(f"⏱️ {time_since_last:.0f} phút sau lệnh thua trước")
            
            # Check 3: Increased position size
            if session_stats.avg_position_size > 0:
                size_ratio = current_quantity / session_stats.avg_position_size
                
                if size_ratio > 2:
                    score += 35
                    reasons.append(f"📊 Size TĂNG MẠNH: gấp {size_ratio:.1f}x bình thường!")
                elif size_ratio > 1.5:
                    score += 25
                    reasons.append(f"📊 Size tăng: +{((size_ratio-1)*100):.0f}% so với TB")
                elif size_ratio > 1.3:
                    score += 15
                    reasons.append(f"📊 Size tăng nhẹ: +{((size_ratio-1)*100):.0f}%")
            
            # Check 4: Session in drawdown
            if session_stats.current_drawdown_pct > 5:
                score += 20
                reasons.append(f"📉 Đang drawdown {session_stats.current_drawdown_pct:.1f}% trong session")
            
            # Check 5: Losing streak
            recent_losses = sum(1 for t in session_stats.last_trades[-5:] if t.pnl < 0)
            if recent_losses >= 3:
                score += 25
                reasons.append(f"🔴 Đã thua {recent_losses} lệnh liên tiếp!")
        
        # Check 6: Keywords in notes
        if notes:
            note_lower = notes.lower()
            matched_keywords = [k for k in self.REVENGE_KEYWORDS if k in note_lower]
            
            if matched_keywords:
                keyword_score = min(len(matched_keywords) * 20, 40)
                score += keyword_score
                reasons.append(f"🔍 Phát hiện tâm lý REVENGE: {', '.join(matched_keywords[:2])}")
        
        # Generate alert if score is high enough
        if score >= 50:
            severity = self._get_severity(score)
            
            if score >= 80:
                recommendation = "🛑 DỪNG NGAY! Bạn đang revenge trade. Nghỉ ít nhất 1 TIẾNG trước khi trade tiếp!"
            elif score >= 60:
                recommendation = "⚠️ NGUY HIỂM: Nghỉ ít nhất 30 phút. Nếu vẫn trade, giảm size 50%."
            else:
                recommendation = "💡 Cảnh giác: Kiểm tra lại tâm lý. Có đang muốn gỡ không?"
            
            return Alert(
                alert_type="REVENGE_TRADING",
                severity=severity,
                score=score,
                reasons=reasons,
                recommendation=recommendation
            )
        
        return None
    
    def _get_severity(self, score: int) -> str:
        """Get severity level based on score"""
        if score >= 80:
            return "CRITICAL"
        elif score >= 60:
            return "HIGH"
        elif score >= 50:
            return "MEDIUM"
        else:
            return "INFO"
