"""
Tilt Detector - Phát hiện trạng thái tilt (emotional trading)
"""

from dataclasses import dataclass, field
from typing import Optional, List
from datetime import datetime, timedelta


@dataclass
class SessionStats:
    """User session statistics"""
    trade_count: int = 0
    win_count: int = 0
    loss_count: int = 0
    session_pnl: float = 0.0
    current_drawdown_pct: float = 0.0
    session_duration_hours: float = 0.0
    avg_trades_per_hour: float = 1.0
    trades_last_hour: int = 0


@dataclass
class Alert:
    """Alert generated by detector"""
    alert_type: str
    severity: str
    score: int
    reasons: List[str] = field(default_factory=list)
    recommendation: str = ""
    
    def to_dict(self) -> dict:
        return {
            "alert_type": self.alert_type,
            "severity": self.severity,
            "score": self.score,
            "reasons": self.reasons,
            "recommendation": self.recommendation
        }


class TiltDetector:
    """
    Phát hiện Tilt (emotional trading) dựa trên:
    1. Drawdown vượt ngưỡng
    2. Trade frequency tăng đột biến
    3. Win rate session thấp
    4. Nhiều trades trong thời gian ngắn
    5. Keywords thể hiện tâm lý tiêu cực
    """
    
    TILT_KEYWORDS = [
        # Vietnamese - frustration/anger
        "bực", "điên", "tức", "nản", "chán",
        "mệt mỏi", "stress", "áp lực", "không hiểu",
        "sai hoài", "thua mãi", "thị trường điên",
        "market maker", "bị scam", "bị lừa",
        # Vietnamese - desperation  
        "cuối cùng", "lần này phải thắng", "tất tay",
        "load thêm tiền", "nạp thêm", "gỡ bằng mọi giá",
        # English
        "frustrated", "angry", "tilted", "fed up",
        "doesn't make sense", "rigged", "manipulated",
        "one more trade", "last trade", "all in",
        "need to win"
    ]
    
    def detect(
        self,
        notes: Optional[str],
        session_stats: Optional[SessionStats] = None
    ) -> Optional[Alert]:
        """
        Detect tilt (emotional state) in trading.
        
        Args:
            notes: Trade notes from user
            session_stats: Statistics from current trading session
            
        Returns:
            Alert if tilt detected, None otherwise
        """
        score = 0
        reasons = []
        
        if session_stats:
            # Check 1: Current drawdown
            drawdown = session_stats.current_drawdown_pct
            if drawdown > 10:
                score += 45
                reasons.append(f"🔴 Drawdown RẤT CAO: {drawdown:.1f}%!")
            elif drawdown > 7:
                score += 35
                reasons.append(f"🟠 Drawdown cao: {drawdown:.1f}%")
            elif drawdown > 5:
                score += 25
                reasons.append(f"🟡 Đang drawdown: {drawdown:.1f}%")
            elif drawdown > 3:
                score += 10
                reasons.append(f"📉 Drawdown nhẹ: {drawdown:.1f}%")
            
            # Check 2: Trade frequency spike
            if session_stats.avg_trades_per_hour > 0:
                frequency_ratio = session_stats.trades_last_hour / max(session_stats.avg_trades_per_hour, 0.5)
                
                if frequency_ratio > 3:
                    score += 35
                    reasons.append(f"⚡ Trading quá nhiều: gấp {frequency_ratio:.1f}x bình thường!")
                elif frequency_ratio > 2:
                    score += 25
                    reasons.append(f"📈 Trade frequency cao: gấp {frequency_ratio:.1f}x")
                elif frequency_ratio > 1.5:
                    score += 15
                    reasons.append(f"📊 Trade hơi nhiều so với bình thường")
            
            # Check 3: Poor session win rate with enough trades
            if session_stats.trade_count >= 5:
                win_rate = session_stats.win_count / session_stats.trade_count
                
                if win_rate < 0.2:
                    score += 40
                    reasons.append(f"🔴 Win rate session RẤT THẤP: {win_rate*100:.0f}%!")
                elif win_rate < 0.3:
                    score += 30
                    reasons.append(f"🟠 Win rate session thấp: {win_rate*100:.0f}%")
                elif win_rate < 0.4:
                    score += 15
                    reasons.append(f"📉 Win rate session: {win_rate*100:.0f}%")
            
            # Check 4: Too many trades in session
            if session_stats.trade_count > 15:
                score += 25
                reasons.append(f"⚠️ Quá nhiều trades trong session: {session_stats.trade_count}")
            elif session_stats.trade_count > 10:
                score += 15
                reasons.append(f"📊 Nhiều trades trong session: {session_stats.trade_count}")
            
            # Check 5: Long session with poor performance
            if session_stats.session_duration_hours > 4 and session_stats.current_drawdown_pct > 3:
                score += 20
                reasons.append(f"⏰ Trading quá lâu ({session_stats.session_duration_hours:.1f}h) trong lúc thua lỗ")
        
        # Check 6: Tilt keywords in notes
        if notes:
            note_lower = notes.lower()
            matched_keywords = [k for k in self.TILT_KEYWORDS if k in note_lower]
            
            if matched_keywords:
                keyword_score = min(len(matched_keywords) * 15, 35)
                score += keyword_score
                reasons.append(f"🔍 Phát hiện tâm lý TILT: {', '.join(matched_keywords[:3])}")
        
        # Generate alert if score is high enough
        if score >= 50:
            severity = self._get_severity(score)
            
            if score >= 85:
                recommendation = "🛑 DỪNG NGAY VÀ NGHỈ! Bạn đang tilt nghiêm trọng. Không trade trong ít nhất 3-4 tiếng hoặc ngày mai mới trade tiếp."
            elif score >= 70:
                recommendation = "⚠️ NGHỈ NGAY! Tilt detected. Nghỉ ít nhất 2 tiếng. Đi dạo, tập thể dục, hoặc làm việc khác."
            elif score >= 55:
                recommendation = "💡 CẢNH BÁO: Có dấu hiệu tilt. Nghỉ 30-60 phút trước khi tiếp tục."
            else:
                recommendation = "📋 Lưu ý: Tâm lý có thể đang bị ảnh hưởng. Consider taking a break."
            
            return Alert(
                alert_type="TILT",
                severity=severity,
                score=score,
                reasons=reasons,
                recommendation=recommendation
            )
        
        return None
    
    def _get_severity(self, score: int) -> str:
        """Get severity level based on score"""
        if score >= 85:
            return "CRITICAL"
        elif score >= 70:
            return "HIGH"
        elif score >= 55:
            return "MEDIUM"
        else:
            return "INFO"
